// Map Portuguese country names to ISO 2-letter country codes
export const COUNTRY_CODE_MAP: Record<string, string> = {
	"Afeganistão": "AF",
	"Albânia": "AL",
	"Alemanha": "DE",
	"Andorra": "AD",
	"Angola": "AO",
	"Anguila": "AI",
	"Antígua e Barbuda": "AG",
	"Arábia Saudita": "SA",
	"Argélia": "DZ",
	"Argentina": "AR",
	"Armênia": "AM",
	"Aruba": "AW",
	"Austrália": "AU",
	"Áustria": "AT",
	"Azerbaijão": "AZ",
	"Bahamas": "BS",
	"Bahrein": "BH",
	"Bangladesh": "BD",
	"Barbados": "BB",
	"Bélgica": "BE",
	"Belize": "BZ",
	"Benin": "BJ",
	"Bermudas": "BM",
	"Bielorrússia": "BY",
	"Birmânia": "MM",
	"Bolívia": "BO",
	"Bósnia e Herzegovina": "BA",
	"Botsuana": "BW",
	"Brasil": "BR",
	"Brunei": "BN",
	"Bulgária": "BG",
	"Burquina Faso": "BF",
	"Burundi": "BI",
	"Butão": "BT",
	"Cabo Verde": "CV",
	"Camarões": "CM",
	"Camboja": "KH",
	"Canadá": "CA",
	"Catar": "QA",
	"Cazaquistão": "KZ",
	"Chade": "TD",
	"Chile": "CL",
	"China": "CN",
	"Chipre": "CY",
	"Cidade do Vaticano": "VA",
	"Colômbia": "CO",
	"Comores": "KM",
	"Congo": "CG",
	"Coreia do Norte": "KP",
	"Coreia do Sul": "KR",
	"Costa do Marfim": "CI",
	"Costa Rica": "CR",
	"Croácia": "HR",
	"Cuba": "CU",
	"Curaçao": "CW",
	"Dinamarca": "DK",
	"Djibuti": "DJ",
	"Dominica": "DM",
	"Egito": "EG",
	"Emirados Árabes Unidos": "AE",
	"Equador": "EC",
	"Eritreia": "ER",
	"Eslováquia": "SK",
	"Eslovênia": "SI",
	"Espanha": "ES",
	"Estados Unidos": "US",
	"Estônia": "EE",
	"Eswatíni": "SZ",
	"Etiópia": "ET",
	"Fiji": "FJ",
	"Filipinas": "PH",
	"Finlândia": "FI",
	"França": "FR",
	"Gabão": "GA",
	"Gâmbia": "GM",
	"Gana": "GH",
	"Geórgia": "GE",
	"Gibraltar": "GI",
	"Granada": "GD",
	"Granadinas": "VC",
	"Grécia": "GR",
	"Groenlândia": "GL",
	"Guadalupe": "GP",
	"Guam": "GU",
	"Guatemala": "GT",
	"Guernsey": "GG",
	"Guiana": "GY",
	"Guiana Francesa": "GF",
	"Guiné": "GN",
	"Guiné Equatorial": "GQ",
	"Guiné-Bissau": "GW",
	"Haiti": "HT",
	"Honduras": "HN",
	"Hong Kong": "HK",
	"Hungria": "HU",
	"Iêmen": "YE",
	"Ilha Bouvet": "BV",
	"Ilha Christmas": "CX",
	"Ilha de Man": "IM",
	"Ilhas Åland": "AX",
	"Ilhas Cayman": "KY",
	"Ilhas Cocos": "CC",
	"Ilhas Cook": "CK",
	"Ilhas Faroé": "FO",
	"Ilhas Mariana do Norte": "MP",
	"Ilhas Marshall": "MH",
	"Ilhas Pitcairn": "PN",
	"Ilhas Salomão": "SB",
	"Ilhas Turcas e Caicos": "TC",
	"Ilhas Virgens Britânicas": "VG",
	"Ilhas Virgens dos Estados Unidos": "VI",
	"Índia": "IN",
	"Indonésia": "ID",
	"Inglaterra": "GB",
	"Irã": "IR",
	"Iraque": "IQ",
	"Irlanda": "IE",
	"Irlanda do Norte": "GB",
	"Islândia": "IS",
	"Israel": "IL",
	"Itália": "IT",
	"Jamaica": "JM",
	"Japão": "JP",
	"Jersey": "JE",
	"Jordânia": "JO",
	"Kiribati": "KI",
	"Kosovo": "XK",
	"Kuwait": "KW",
	"Laos": "LA",
	"Lesoto": "LS",
	"Letônia": "LV",
	"Líbano": "LB",
	"Libéria": "LR",
	"Líbia": "LY",
	"Liechtenstein": "LI",
	"Lituânia": "LT",
	"Luxemburgo": "LU",
	"Macau": "MO",
	"Macedônia do Norte": "MK",
	"Madagáscar": "MG",
	"Madeira": "PT",
	"Malásia": "MY",
	"Malawi": "MW",
	"Maldivas": "MV",
	"Mali": "ML",
	"Malta": "MT",
	"Marrocos": "MA",
	"Martinica": "MQ",
	"Maurício": "MU",
	"Mauritânia": "MR",
	"Mayotte": "YT",
	"México": "MX",
	"Micronésia": "FM",
	"Moçambique": "MZ",
	"Moldávia": "MD",
	"Mónaco": "MC",
	"Mongólia": "MN",
	"Montenegro": "ME",
	"Montserrat": "MS",
	"Namíbia": "NA",
	"Nauru": "NR",
	"Nepal": "NP",
	"Nicarágua": "NI",
	"Níger": "NE",
	"Nigéria": "NG",
	"Niue": "NU",
	"Noruega": "NO",
	"Nova Caledônia": "NC",
	"Nova Zelândia": "NZ",
	"Omã": "OM",
	"Palestina": "PS",
	"Panamá": "PA",
	"Papua-Nova Guiné": "PG",
	"Paquistão": "PK",
	"Paraguai": "PY",
	"Países Baixos": "NL",
	"País de Gales": "GB",
	"Palau": "PW",
	"Peru": "PE",
	"Polinésia Francesa": "PF",
	"Polônia": "PL",
	"Porto Rico": "PR",
	"Portugal": "PT",
	"Quênia": "KE",
	"Quirguistão": "KG",
	"Reunião": "RE",
	"Romênia": "RO",
	"Ruanda": "RW",
	"Rússia": "RU",
	"Saara Ocidental": "EH",
	"Saint Kitts e Neves": "KN",
	"Saint Lúcia": "LC",
	"Saint Vincent e Granadinas": "VC",
	"Samoa": "WS",
	"Samoa Americana": "AS",
	"San Cristóbal e Neves": "KN",
	"San Marinho": "SM",
	"San Vicente e Granadinas": "VC",
	"Santa Helena": "SH",
	"Santa Lúcia": "LC",
	"Santomé e Príncipe": "ST",
	"Senegal": "SN",
	"Serra Leoa": "SL",
	"Sérvia": "RS",
	"Seychelles": "SC",
	"Síria": "SY",
	"Sint Maarten": "SX",
	"Singapura": "SG",
	"Sint Eustatius": "BQ",
	"Somália": "SO",
	"Sri Lanca": "LK",
	"Suazilândia": "SZ",
	"Sudão": "SD",
	"Sudão do Sul": "SS",
	"Suécia": "SE",
	"Suíça": "CH",
	"Surinã": "SR",
	"Tailândia": "TH",
	"Taiwan": "TW",
	"Tajiquistão": "TJ",
	"Tanzânia": "TZ",
	"República Tcheca": "CZ",
	"Timor-Leste": "TL",
	"Togo": "TG",
	"Tonga": "TO",
	"Trinidad e Tobago": "TT",
	"Tunísia": "TN",
	"Turks e Caicos": "TC",
	"Turcomênia": "TM",
	"Turquia": "TR",
	"Tuvalu": "TV",
	"Ucrânia": "UA",
	"Uganda": "UG",
	"Uruguai": "UY",
	"Uzbequistão": "UZ",
	"Vanuatu": "VU",
	"Vaticano": "VA",
	"Venezuela": "VE",
	"Vietnã": "VN",
	"Vietname": "VN",
	"Wallis e Futuna": "WF",
	"Zâmbia": "ZM",
	"Zimbábue": "ZW",
};
