export const NATIONALITY_OPTIONS = [
	"Afeganistão",
	"Albânia",
	"Alemanha",
	"Andorra",
	"Angola",
	"Anguila",
	"Antígua e Barbuda",
	"Arábia Saudita",
	"Argélia",
	"Argentina",
	"Armênia",
	"Aruba",
	"Austrália",
	"Áustria",
	"Azerbaijão",
	"Bahamas",
	"Bahrein",
	"Bangladesh",
	"Barbados",
	"Bélgica",
	"Belize",
	"Benin",
	"Bermudas",
	"Bielorrússia",
	"Birmânia",
	"Bolívia",
	"Bósnia e Herzegovina",
	"Botsuana",
	"Brasil",
	"Brunei",
	"Bulgária",
	"Burquina Faso",
	"Burundi",
	"Butão",
	"Cabo Verde",
	"Camarões",
	"Camboja",
	"Canadá",
	"Catar",
	"Cazaquistão",
	"Chade",
	"Chile",
	"China",
	"Chipre",
	"Cidade do Vaticano",
	"Colômbia",
	"Comores",
	"Congo",
	"Coreia do Norte",
	"Coreia do Sul",
	"Costa do Marfim",
	"Costa Rica",
	"Croácia",
	"Cuba",
	"Curaçao",
	"Dinamarca",
	"Djibuti",
	"Dominica",
	"Egito",
	"Emirados Árabes Unidos",
	"Equador",
	"Eritreia",
	"Eslováquia",
	"Eslovênia",
	"Espanha",
	"Estados Unidos",
	"Estônia",
	"Eswatíni",
	"Etiópia",
	"Fiji",
	"Filipinas",
	"Finlândia",
	"França",
	"Gabão",
	"Gâmbia",
	"Gana",
	"Geórgia",
	"Gibraltar",
	"Granada",
	"Granadinas",
	"Grécia",
	"Groenlândia",
	"Guadalupe",
	"Guam",
	"Guatemala",
	"Guernsey",
	"Guiana",
	"Guiana Francesa",
	"Guiné",
	"Guiné Equatorial",
	"Guiné-Bissau",
	"Haiti",
	"Honduras",
	"Hong Kong",
	"Hungria",
	"Iêmen",
	"Ilha Bouvet",
	"Ilha Christmas",
	"Ilha de Man",
	"Ilhas Åland",
	"Ilhas Cayman",
	"Ilhas Cocos",
	"Ilhas Cook",
	"Ilhas Faroé",
	"Ilhas Mariana do Norte",
	"Ilhas Marshall",
	"Ilhas Pitcairn",
	"Ilhas Salomão",
	"Ilhas Turcas e Caicos",
	"Ilhas Virgens Britânicas",
	"Ilhas Virgens dos Estados Unidos",
	"Índia",
	"Indonésia",
	"Inglaterra",
	"Irã",
	"Iraque",
	"Irlanda",
	"Irlanda do Norte",
	"Islândia",
	"Israel",
	"Itália",
	"Jamaica",
	"Japão",
	"Jersey",
	"Jordânia",
	"Kiribati",
	"Kosovo",
	"Kuwait",
	"Laos",
	"Lesoto",
	"Letônia",
	"Líbano",
	"Libéria",
	"Líbia",
	"Liechtenstein",
	"Lituânia",
	"Luxemburgo",
	"Macau",
	"Macedônia do Norte",
	"Madagáscar",
	"Madeira",
	"Malásia",
	"Malawi",
	"Maldivas",
	"Mali",
	"Malta",
	"Marrocos",
	"Martinica",
	"Maurício",
	"Mauritânia",
	"Mayotte",
	"México",
	"Micronésia",
	"Moçambique",
	"Moldávia",
	"Mónaco",
	"Mongólia",
	"Montenegro",
	"Montserrat",
	"Namíbia",
	"Nauru",
	"Nepal",
	"Nicarágua",
	"Níger",
	"Nigéria",
	"Niue",
	"Noruega",
	"Nova Caledônia",
	"Nova Zelândia",
	"Omã",
	"Palestina",
	"Panamá",
	"Papua-Nova Guiné",
	"Paquistão",
	"Paraguai",
	"Países Baixos",
	"País de Gales",
	"Palau",
	"Peru",
	"Polinésia Francesa",
	"Polônia",
	"Porto Rico",
	"Portugal",
	"Quênia",
	"Quirguistão",
	"Reunião",
	"Romênia",
	"Ruanda",
	"Rússia",
	"Saara Ocidental",
	"Saint Kitts e Neves",
	"Saint Lúcia",
	"Saint Vincent e Granadinas",
	"Samoa",
	"Samoa Americana",
	"San Cristóbal e Neves",
	"San Marinho",
	"San Vicente e Granadinas",
	"Santa Helena",
	"Santa Lúcia",
	"Santomé e Príncipe",
	"Senegal",
	"Serra Leoa",
	"Sérvia",
	"Seychelles",
	"Síria",
	"Sint Maarten",
	"Singapura",
	"Sint Eustatius",
	"Somália",
	"Sri Lanca",
	"Suazilândia",
	"Sudão",
	"Sudão do Sul",
	"Suécia",
	"Suíça",
	"Surinã",
	"Tailândia",
	"Taiwan",
	"Tajiquistão",
	"Tanzânia",
	"Tcheca",
	"República Tcheca",
	"Timor-Leste",
	"Togo",
	"Tonga",
	"Trinidad e Tobago",
	"Tunísia",
	"Turks e Caicos",
	"Turcomênia",
	"Turquia",
	"Turcomenistão",
	"Tuvalu",
	"Ucrânia",
	"Uganda",
	"União Europeia",
	"Uruguai",
	"Uzbequistão",
	"Vanuatu",
	"Vaticano",
	"Venezuela",
	"Vietnã",
	"Vietname",
	"Wallis e Futuna",
	"Zâmbia",
	"Zimbábue",
];
