export const NATIONALITY_OPTIONS: { label: string; code: string }[] = [
	{ label: "Afeganistão", code: "AF" },
	{ label: "Albânia", code: "AL" },
	{ label: "Alemanha", code: "DE" },
	{ label: "Andorra", code: "AD" },
	{ label: "Angola", code: "AO" },
	{ label: "Anguila", code: "AI" },
	{ label: "Antígua e Barbuda", code: "AG" },
	{ label: "Arábia Saudita", code: "SA" },
	{ label: "Argélia", code: "DZ" },
	{ label: "Argentina", code: "AR" },
	{ label: "Armênia", code: "AM" },
	{ label: "Aruba", code: "AW" },
	{ label: "Austrália", code: "AU" },
	{ label: "Áustria", code: "AT" },
	{ label: "Azerbaijão", code: "AZ" },
	{ label: "Bahamas", code: "BS" },
	{ label: "Bahrein", code: "BH" },
	{ label: "Bangladesh", code: "BD" },
	{ label: "Barbados", code: "BB" },
	{ label: "Bélgica", code: "BE" },
	{ label: "Belize", code: "BZ" },
	{ label: "Benin", code: "BJ" },
	{ label: "Bermudas", code: "BM" },
	{ label: "Bielorrússia", code: "BY" },
	{ label: "Birmânia", code: "MM" },
	{ label: "Bolívia", code: "BO" },
	{ label: "Bósnia e Herzegovina", code: "BA" },
	{ label: "Botsuana", code: "BW" },
	{ label: "Brasil", code: "BR" },
	{ label: "Brunei", code: "BN" },
	{ label: "Bulgária", code: "BG" },
	{ label: "Burquina Faso", code: "BF" },
	{ label: "Burundi", code: "BI" },
	{ label: "Butão", code: "BT" },
	{ label: "Cabo Verde", code: "CV" },
	{ label: "Camarões", code: "CM" },
	{ label: "Camboja", code: "KH" },
	{ label: "Canadá", code: "CA" },
	{ label: "Catar", code: "QA" },
	{ label: "Cazaquistão", code: "KZ" },
	{ label: "Chade", code: "TD" },
	{ label: "Chile", code: "CL" },
	{ label: "China", code: "CN" },
	{ label: "Chipre", code: "CY" },
	{ label: "Cidade do Vaticano", code: "VA" },
	{ label: "Colômbia", code: "CO" },
	{ label: "Comores", code: "KM" },
	{ label: "Congo", code: "CG" },
	{ label: "Coreia do Norte", code: "KP" },
	{ label: "Coreia do Sul", code: "KR" },
	{ label: "Costa do Marfim", code: "CI" },
	{ label: "Costa Rica", code: "CR" },
	{ label: "Croácia", code: "HR" },
	{ label: "Cuba", code: "CU" },
	{ label: "Curaçao", code: "CW" },
	{ label: "Dinamarca", code: "DK" },
	{ label: "Djibuti", code: "DJ" },
	{ label: "Dominica", code: "DM" },
	{ label: "Egito", code: "EG" },
	{ label: "Emirados Árabes Unidos", code: "AE" },
	{ label: "Equador", code: "EC" },
	{ label: "Eritreia", code: "ER" },
	{ label: "Eslováquia", code: "SK" },
	{ label: "Eslovênia", code: "SI" },
	{ label: "Espanha", code: "ES" },
	{ label: "Estados Unidos", code: "US" },
	{ label: "Estônia", code: "EE" },
	{ label: "Eswatíni", code: "SZ" },
	{ label: "Etiópia", code: "ET" },
	{ label: "Fiji", code: "FJ" },
	{ label: "Filipinas", code: "PH" },
	{ label: "Finlândia", code: "FI" },
	{ label: "França", code: "FR" },
	{ label: "Gabão", code: "GA" },
	{ label: "Gâmbia", code: "GM" },
	{ label: "Gana", code: "GH" },
	{ label: "Geórgia", code: "GE" },
	{ label: "Gibraltar", code: "GI" },
	{ label: "Granada", code: "GD" },
	{ label: "Grécia", code: "GR" },
	{ label: "Groenlândia", code: "GL" },
	{ label: "Guadalupe", code: "GP" },
	{ label: "Guam", code: "GU" },
	{ label: "Guatemala", code: "GT" },
	{ label: "Guernsey", code: "GG" },
	{ label: "Guiana", code: "GY" },
	{ label: "Guiana Francesa", code: "GF" },
	{ label: "Guiné", code: "GN" },
	{ label: "Guiné Equatorial", code: "GQ" },
	{ label: "Guiné-Bissau", code: "GW" },
	{ label: "Haiti", code: "HT" },
	{ label: "Honduras", code: "HN" },
	{ label: "Hong Kong", code: "HK" },
	{ label: "Hungria", code: "HU" },
	{ label: "Iêmen", code: "YE" },
	{ label: "Ilha Bouvet", code: "BV" },
	{ label: "Ilha Christmas", code: "CX" },
	{ label: "Ilha de Man", code: "IM" },
	{ label: "Ilhas Åland", code: "AX" },
	{ label: "Ilhas Cayman", code: "KY" },
	{ label: "Ilhas Cocos", code: "CC" },
	{ label: "Ilhas Cook", code: "CK" },
	{ label: "Ilhas Faroé", code: "FO" },
	{ label: "Ilhas Mariana do Norte", code: "MP" },
	{ label: "Ilhas Marshall", code: "MH" },
	{ label: "Ilhas Pitcairn", code: "PN" },
	{ label: "Ilhas Salomão", code: "SB" },
	{ label: "Ilhas Turcas e Caicos", code: "TC" },
	{ label: "Ilhas Virgens Britânicas", code: "VG" },
	{ label: "Ilhas Virgens dos Estados Unidos", code: "VI" },
	{ label: "Índia", code: "IN" },
	{ label: "Indonésia", code: "ID" },
	{ label: "Inglaterra", code: "GB" },
	{ label: "Irã", code: "IR" },
	{ label: "Iraque", code: "IQ" },
	{ label: "Irlanda", code: "IE" },
	{ label: "Irlanda do Norte", code: "GB" },
	{ label: "Islândia", code: "IS" },
	{ label: "Israel", code: "IL" },
	{ label: "Itália", code: "IT" },
	{ label: "Jamaica", code: "JM" },
	{ label: "Japão", code: "JP" },
	{ label: "Jersey", code: "JE" },
	{ label: "Jordânia", code: "JO" },
	{ label: "Kiribati", code: "KI" },
	{ label: "Kosovo", code: "XK" },
	{ label: "Kuwait", code: "KW" },
	{ label: "Laos", code: "LA" },
	{ label: "Lesoto", code: "LS" },
	{ label: "Letônia", code: "LV" },
	{ label: "Líbano", code: "LB" },
	{ label: "Libéria", code: "LR" },
	{ label: "Líbia", code: "LY" },
	{ label: "Liechtenstein", code: "LI" },
	{ label: "Lituânia", code: "LT" },
	{ label: "Luxemburgo", code: "LU" },
	{ label: "Macau", code: "MO" },
	{ label: "Macedônia do Norte", code: "MK" },
	{ label: "Madagáscar", code: "MG" },
	{ label: "Madeira", code: "PT" },
	{ label: "Malásia", code: "MY" },
	{ label: "Malawi", code: "MW" },
	{ label: "Maldivas", code: "MV" },
	{ label: "Mali", code: "ML" },
	{ label: "Malta", code: "MT" },
	{ label: "Marrocos", code: "MA" },
	{ label: "Martinica", code: "MQ" },
	{ label: "Maurício", code: "MU" },
	{ label: "Mauritânia", code: "MR" },
	{ label: "Mayotte", code: "YT" },
	{ label: "México", code: "MX" },
	{ label: "Micronésia", code: "FM" },
	{ label: "Moçambique", code: "MZ" },
	{ label: "Moldávia", code: "MD" },
	{ label: "Mônaco", code: "MC" },
	{ label: "Mongólia", code: "MN" },
	{ label: "Montenegro", code: "ME" },
	{ label: "Montserrat", code: "MS" },
	{ label: "Namíbia", code: "NA" },
	{ label: "Nauru", code: "NR" },
	{ label: "Nepal", code: "NP" },
	{ label: "Nicarágua", code: "NI" },
	{ label: "Níger", code: "NE" },
	{ label: "Nigéria", code: "NG" },
	{ label: "Niue", code: "NU" },
	{ label: "Noruega", code: "NO" },
	{ label: "Nova Caledônia", code: "NC" },
	{ label: "Nova Zelândia", code: "NZ" },
	{ label: "Omã", code: "OM" },
	{ label: "Palestina", code: "PS" },
	{ label: "Panamá", code: "PA" },
	{ label: "Papua-Nova Guiné", code: "PG" },
	{ label: "Paquistão", code: "PK" },
	{ label: "Paraguai", code: "PY" },
	{ label: "Países Baixos", code: "NL" },
	{ label: "País de Gales", code: "GB" },
	{ label: "Palau", code: "PW" },
	{ label: "Peru", code: "PE" },
	{ label: "Polinésia Francesa", code: "PF" },
	{ label: "Polônia", code: "PL" },
	{ label: "Porto Rico", code: "PR" },
	{ label: "Portugal", code: "PT" },
	{ label: "Quênia", code: "KE" },
	{ label: "Quirguistão", code: "KG" },
	{ label: "Reunião", code: "RE" },
	{ label: "Romênia", code: "RO" },
	{ label: "Ruanda", code: "RW" },
	{ label: "Rússia", code: "RU" },
	{ label: "Saara Ocidental", code: "EH" },
	{ label: "Saint Kitts e Neves", code: "KN" },
	{ label: "Saint Lúcia", code: "LC" },
	{ label: "Saint Vincent e Granadinas", code: "VC" },
	{ label: "Samoa", code: "WS" },
	{ label: "Samoa Americana", code: "AS" },
	{ label: "San Marinho", code: "SM" },
	{ label: "Santa Helena", code: "SH" },
	{ label: "Santomé e Príncipe", code: "ST" },
	{ label: "Senegal", code: "SN" },
	{ label: "Serra Leoa", code: "SL" },
	{ label: "Sérvia", code: "RS" },
	{ label: "Seychelles", code: "SC" },
	{ label: "Síria", code: "SY" },
	{ label: "Sint Maarten", code: "SX" },
	{ label: "Singapura", code: "SG" },
	{ label: "Somália", code: "SO" },
	{ label: "Sri Lanka", code: "LK" },
	{ label: "Sudão", code: "SD" },
	{ label: "Sudão do Sul", code: "SS" },
	{ label: "Suécia", code: "SE" },
	{ label: "Suíça", code: "CH" },
	{ label: "Suriname", code: "SR" },
	{ label: "Tailândia", code: "TH" },
	{ label: "Taiwan", code: "TW" },
	{ label: "Tajiquistão", code: "TJ" },
	{ label: "Tanzânia", code: "TZ" },
	{ label: "República Tcheca", code: "CZ" },
	{ label: "Timor-Leste", code: "TL" },
	{ label: "Togo", code: "TG" },
	{ label: "Tonga", code: "TO" },
	{ label: "Trinidad e Tobago", code: "TT" },
	{ label: "Tunísia", code: "TN" },
	{ label: "Turquia", code: "TR" },
	{ label: "Turcomenistão", code: "TM" },
	{ label: "Tuvalu", code: "TV" },
	{ label: "Ucrânia", code: "UA" },
	{ label: "Uganda", code: "UG" },
	{ label: "Uruguai", code: "UY" },
	{ label: "Uzbequistão", code: "UZ" },
	{ label: "Vanuatu", code: "VU" },
	{ label: "Venezuela", code: "VE" },
	{ label: "Vietnã", code: "VN" },
	{ label: "Wallis e Futuna", code: "WF" },
	{ label: "Zâmbia", code: "ZM" },
	{ label: "Zimbábue", code: "ZW" },
];
