query GetSeasonRounds($slug: String!) {
	rounds(
		where: { season: { slug: $slug } }
		stage: PUBLISHED
		orderBy: date_ASC
	) {
		id
		name
		link
		date

	}
}

query GetDrivers {
	drivers(stage: DRAFT, where: { deleted: false }) {
		id
		grid
		name
		class
		number
		stream
		deleted
		photo {
			url
		}
		badgeTitle
		badge {
			url
		}
		city
		equipment
		phone
		team {
			id
			name
			color {
				hex
			}
			photo {
				id
				url
			}
		}
	}
}

query GetDriversRegistration {
	drivers(orderBy: name_ASC, stage: DRAFT, where: { deleted: false }) {
		id
		grid
		class
		name
		number
		stream
		deleted
		photo {
			id
			url
		}
		badgeTitle
		badge {
			id
			url
		}
		city
		equipment
		phone
		team {
			id
			name
			color {
				hex
			}
			photo {
				id
				url
			}
		}
	}
}

query GridOptions {
	__type(name: "Grid") {
		enumValues {
			name
		}
	}
}

query ClassOptions {
	__type(name: "Class") {
		enumValues {
			name
		}
	}
}

query GetRoundResults($id: ID!) {
	round(where: { id: $id }, stage: PUBLISHED) {
		id
		name
		date
		link
		season {
			name
		}

		results
	}
}
