enum Grid {
	gridA
	gridB
	gridC
}

query GetStatsData($gridId: Grid!) {
	datas(
		stage: DRAFT
		orderBy: createdAt_DESC
		first: 2
		where: { deleted: false, grid: $gridId }
	) {
		id
		title
		grid
		csv {
			url
		}
	}
}

query GetData {
	datas(stage: DRAFT, orderBy: createdAt_DESC, where: { deleted: false }) {
		id
		title
		grid
		deleted
		createdAt
		csv {
			url
		}
	}
}

# query GetStatsDataA {
# 	datas(
# 		stage: DRAFT
# 		orderBy: createdAt_DESC
# 		first: 2
# 		where: { grid: gridA, deleted: false }
# 	) {
# 		id
# 		csv {
# 			url
# 		}
# 		grid
# 	}
# }
# query GetStatsDataB {
# 	datas(
# 		stage: DRAFT
# 		orderBy: createdAt_DESC
# 		first: 2
# 		where: { grid: gridB, deleted: false }
# 	) {
# 		id
# 		csv {
# 			url
# 		}
# 		grid
# 	}
# }

# query GetStatsDataC {
# 	datas(
# 		stage: DRAFT
# 		orderBy: createdAt_DESC
# 		first: 2
# 		where: { grid: gridC, deleted: false }
# 	) {
# 		id
# 		csv {
# 			url
# 		}
# 		grid
# 	}
# }
