query GetBanners {
	banners(stage: DRAFT, orderBy: createdAt_DESC, where: { deleted: false }) {
		id
		title
		content
		link
		deleted
		category
		photo {
			id
			url
		}
		createdAt
		updatedAt
	}
}

query GetBannersRegistration {
	banners(orderBy: createdAt_DESC, stage: DRAFT, where: { deleted: false }) {
		id
		title
		content
		link
		deleted
		category
		photo {
			id
			url
		}
		createdAt
	}
}

query GetBannersCategories {
	__type(name: "NewsCategory") {
		enumValues {
			name
		}
	}
}
