query GetCalendars {
	calendars(
		orderBy: date_ASC
		where: { active: true, deleted: false }
		stage: DRAFT
	) {
		id
		trackId
		sprint
		round
		link
		grid
		deleted
		date
		winnerA {
			id
			name
			grid
			class
			photo {
				id
				url
			}
			team {
				id
				color {
					hex
				}
			}
		}
		winnerB {
			name
			id
			photo {
				url
				id
			}
			team {
				id
				color {
					hex
				}
			}
			grid
			class
		}
	}
}

query GetCalendarsRegistration {
	calendars(orderBy: date_ASC, stage: DRAFT, where: { deleted: false }) {
		id
		trackId
		sprint
		round
		link
		grid
		deleted
		active
		date
		winnerA {
			id
			name
			grid
			class
			photo {
				id
				url
			}
			team {
				id
				color {
					hex
				}
			}
		}
		winnerB {
			name
			id
			photo {
				url
				id
			}
			team {
				id
				color {
					hex
				}
			}
			grid
			class
		}
	}
}
