query GetCalendars {
	calendars(
		orderBy: date_ASC
		where: { active: true, deleted: false }
		stage: PUBLISHED
	) {
		id
		track
		round
		active
		deleted
		winnerA
		winnerB
		map {
			url
		}
		grid
		description
		date
		link
		flag {
			url
		}
	}
}

query GetCalendarsRegistration {
	calendars(orderBy: date_ASC, stage: DRAFT, where: { deleted: false }) {
		id
		track
		round
		winnerA
		winnerB
		active
		map {
			url
		}
		grid
		deleted
		description
		date
		link
		flag {
			url
		}
	}
}
